# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y jq
        docker pull greymd/egison-deb-builder:latest
        docker pull greymd/egison-rpm-builder:latest
        docker pull greymd/egison-tarball-builder:latest

    - name: Deploy
      env:
        ID_RSA: ${{secrets.ID_RSA}}
        API_AUTH: ${{secrets.API_AUTH}}
        TARGET: egison/egison
      run: |
        bash -x release.sh init
        bash -x release.sh bump "$GITHUB_REPOSITORY" "$TARGET"
        bash -x release.sh upload-tarball "$GITHUB_REPOSITORY" "$TARGET" "$GITHUB_REPOSITORY"
        bash -x release.sh upload-rpm "$GITHUB_REPOSITORY" "$TARGET" "$GITHUB_REPOSITORY"
        bash -x release.sh upload-deb "$GITHUB_REPOSITORY" "$TARGET" "$GITHUB_REPOSITORY"
        bash -x release.sh commit-rpm "$GITHUB_REPOSITORY" "$TARGET" "$GITHUB_REPOSITORY"
        bash -x release.sh commit-deb "$GITHUB_REPOSITORY" "$TARGET" "$GITHUB_REPOSITORY"
